name: SonarCloud Check .NET API 

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
    - name: Use .NET Build, Test, SonarCloud and Publish Action
      uses: ArtyProf/dotnet-build-test-publish-action@v1.1.0
      with:
        sonar-project-key: 'ArtyProf_Arty-App'
        sonar-token: ${{ secrets.SONAR_TOKEN_API }}
        sonar-organization: ''
        dotnet-solution-path: './api/ArtyApp/ArtyApp.sln'
        dotnet-version: '6.0.x'
