name: SonarCloud Check .NET API 

on:
  push:
    branches:
      - master
    paths:
      - api/*
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
    - name: Use .NET Build, Test, SonarCloud check and Publish Action
      uses: ArtyProf/dotnet-build-test-publish-action@v1
      with:
        sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        sonar-organization: ${{ secrets.SONAR_ORGANIZATION }}
